project_id = "xxigtbxqgbdcfpmnrzvp"

[functions.send-contact-email]
verify_jwt = false

[functions.serve-index]
verify_jwt = false

[functions.proxy-storage]
verify_jwt = false

[functions.proxy-data]
verify_jwt = false