
hero:
  title: romergarcia
  subtitle: I create immersive digital experiences that blend storytelling with cutting-edge technology. Expert in leading Creative Teams
  cta_text: View My Work
  cta_section: portfolio
  video_url: staticglitchy.mp4

portfolio:
  title: Portfolio
  description: "Romer Garcia's Portfolio"

about:
  title: About Me
  description: Learn more about my journey and expertise

contact:
  title: Contact
  description: Get in touch with me
  get_in_touch_text: Interested in collaborating? Let's discuss your next project.

