CREATE TABLE public.paradoxxia_carousel (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  image_url text NOT NULL,
  title text,
  description text,
  link_url text,
  sort_order integer DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now()
);

ALTER TABLE public.paradoxxia_carousel ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access to paradoxxia_carousel"
  ON public.paradoxxia_carousel
  FOR SELECT
  TO anon, authenticated
  USING (true);